### ISSUE TITLE
Why need to remove image mean?

### ISSUE THREAD

**Issue by MrXu** [rcmalli/keras-squeezenet#2]
In the example code, I found:
```
# Remove image mean
im[:, :, 0] -= 104.006
im[:, :, 1] -= 116.669
im[:, :, 2] -= 122.679
```
May I know why we need to remove the mean of image?
Thanks for your time.

**Comment by rcmalli** [comment]
It is the general step of  ImageNet pre-trained models. You may also find it in the original repository of SqueezeNet or other pre-trained models.
